services:
  db:
    image: mysql:8.0
    container_name: hotelhub-mysql
    restart: always
    environment:
      MYSQL_DATABASE: hotelhub_db
      MYSQL_ROOT_PASSWORD: duy0410hihi
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
